### ISSUE TITLE
NLog 4.0

### ISSUE THREAD

**Issue by kfrancis** [uhaciogullari/NLog.Interface#9]
http://nlog-project.org/2015/06/09/nlog-4-has-been-released.html

**Comment by uhaciogullari** [comment]
Hello Kori, thanks for the PR.

Checking the NLog source code, I see that they created an ILogger interface finally. It makes this library completely redundant. 

If you still need to support the new version with NLog.Interface for some reason I'll merge the PR and create the package. Otherwise I'll put a note that NLog 4.0 makes this library obselete.

**Comment by uhaciogullari** [comment]
@kfrancis ping.

**Comment by kfrancis** [comment]
It's alright, I also saw the new interface available in 4.0.0 - you can just ignore this then, it's not really necessary for 4+
